// Generated by gencpp from file airsim_car_ros_pkgs/Collision.msg
// DO NOT EDIT!


#ifndef AIRSIM_CAR_ROS_PKGS_MESSAGE_COLLISION_H
#define AIRSIM_CAR_ROS_PKGS_MESSAGE_COLLISION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace airsim_car_ros_pkgs
{
template <class ContainerAllocator>
struct Collision_
{
  typedef Collision_<ContainerAllocator> Type;

  Collision_()
    : header()
    , collision_detected(false)
    , collision_count(0)  {
    }
  Collision_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , collision_detected(false)
    , collision_count(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _collision_detected_type;
  _collision_detected_type collision_detected;

   typedef uint32_t _collision_count_type;
  _collision_count_type collision_count;





  typedef boost::shared_ptr< ::airsim_car_ros_pkgs::Collision_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::airsim_car_ros_pkgs::Collision_<ContainerAllocator> const> ConstPtr;

}; // struct Collision_

typedef ::airsim_car_ros_pkgs::Collision_<std::allocator<void> > Collision;

typedef boost::shared_ptr< ::airsim_car_ros_pkgs::Collision > CollisionPtr;
typedef boost::shared_ptr< ::airsim_car_ros_pkgs::Collision const> CollisionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::airsim_car_ros_pkgs::Collision_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::airsim_car_ros_pkgs::Collision_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::airsim_car_ros_pkgs::Collision_<ContainerAllocator1> & lhs, const ::airsim_car_ros_pkgs::Collision_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.collision_detected == rhs.collision_detected &&
    lhs.collision_count == rhs.collision_count;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::airsim_car_ros_pkgs::Collision_<ContainerAllocator1> & lhs, const ::airsim_car_ros_pkgs::Collision_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace airsim_car_ros_pkgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::airsim_car_ros_pkgs::Collision_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::airsim_car_ros_pkgs::Collision_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::airsim_car_ros_pkgs::Collision_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::airsim_car_ros_pkgs::Collision_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::airsim_car_ros_pkgs::Collision_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::airsim_car_ros_pkgs::Collision_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::airsim_car_ros_pkgs::Collision_<ContainerAllocator> >
{
  static const char* value()
  {
    return "132785abdef999140dfbb59e22a1f16f";
  }

  static const char* value(const ::airsim_car_ros_pkgs::Collision_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x132785abdef99914ULL;
  static const uint64_t static_value2 = 0x0dfbb59e22a1f16fULL;
};

template<class ContainerAllocator>
struct DataType< ::airsim_car_ros_pkgs::Collision_<ContainerAllocator> >
{
  static const char* value()
  {
    return "airsim_car_ros_pkgs/Collision";
  }

  static const char* value(const ::airsim_car_ros_pkgs::Collision_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::airsim_car_ros_pkgs::Collision_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"bool collision_detected\n"
"uint32 collision_count\n"
"# string vehicle_name\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::airsim_car_ros_pkgs::Collision_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::airsim_car_ros_pkgs::Collision_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.collision_detected);
      stream.next(m.collision_count);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Collision_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::airsim_car_ros_pkgs::Collision_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::airsim_car_ros_pkgs::Collision_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "collision_detected: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.collision_detected);
    s << indent << "collision_count: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.collision_count);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AIRSIM_CAR_ROS_PKGS_MESSAGE_COLLISION_H
