# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from shell_simulation/CarCmd.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class CarCmd(genpy.Message):
  _md5sum = "ba7c9338c4c7891d8ccba23fd757db82"
  _type = "shell_simulation/CarCmd"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float64 throttle
float64 steering
float64 brake
bool handbrake
bool is_manual_gear
int32 manual_gear
bool gear_immediate
# string vehicle_name
"""
  __slots__ = ['throttle','steering','brake','handbrake','is_manual_gear','manual_gear','gear_immediate']
  _slot_types = ['float64','float64','float64','bool','bool','int32','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       throttle,steering,brake,handbrake,is_manual_gear,manual_gear,gear_immediate

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(CarCmd, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.throttle is None:
        self.throttle = 0.
      if self.steering is None:
        self.steering = 0.
      if self.brake is None:
        self.brake = 0.
      if self.handbrake is None:
        self.handbrake = False
      if self.is_manual_gear is None:
        self.is_manual_gear = False
      if self.manual_gear is None:
        self.manual_gear = 0
      if self.gear_immediate is None:
        self.gear_immediate = False
    else:
      self.throttle = 0.
      self.steering = 0.
      self.brake = 0.
      self.handbrake = False
      self.is_manual_gear = False
      self.manual_gear = 0
      self.gear_immediate = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3d2BiB().pack(_x.throttle, _x.steering, _x.brake, _x.handbrake, _x.is_manual_gear, _x.manual_gear, _x.gear_immediate))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 31
      (_x.throttle, _x.steering, _x.brake, _x.handbrake, _x.is_manual_gear, _x.manual_gear, _x.gear_immediate,) = _get_struct_3d2BiB().unpack(str[start:end])
      self.handbrake = bool(self.handbrake)
      self.is_manual_gear = bool(self.is_manual_gear)
      self.gear_immediate = bool(self.gear_immediate)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3d2BiB().pack(_x.throttle, _x.steering, _x.brake, _x.handbrake, _x.is_manual_gear, _x.manual_gear, _x.gear_immediate))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 31
      (_x.throttle, _x.steering, _x.brake, _x.handbrake, _x.is_manual_gear, _x.manual_gear, _x.gear_immediate,) = _get_struct_3d2BiB().unpack(str[start:end])
      self.handbrake = bool(self.handbrake)
      self.is_manual_gear = bool(self.is_manual_gear)
      self.gear_immediate = bool(self.gear_immediate)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3d2BiB = None
def _get_struct_3d2BiB():
    global _struct_3d2BiB
    if _struct_3d2BiB is None:
        _struct_3d2BiB = struct.Struct("<3d2BiB")
    return _struct_3d2BiB
